cookery/cookery/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("courses/", include("courses.urls"))
]+ debug_toolbar_urls()

cookery/courses/urls.py
from django.urls import path

from . import views

app_name = "courses"


urlpatterns = [
    path("", views.CoursesView.as_view(), name="course"),
    path("<int:pk>/", views.CoutsesDetailsView.as_view(), name="course_details"),
    path("instructor", views.InstructorView.as_view(), name="instructor"),
    path("instructor/<int:pk>/", views.InstructorDetailsView.as_view(), name="instructor_details"),
    path("<int:course_id>/add/", views.add, name="add"),
]

cookery/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

cookery/courses/models.py
from django.db import models
from django.contrib.auth import get_user_model
from users.models import UserAccount
# Create your models here.

class Course(models.Model):
    instructor = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    details = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

cookery/users/models.py
from django.db import models

# Create your models here.

from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone


class UserAccountManager(BaseUserManager):

  def create_user(self, email, password=None, **kwargs):
    if not email:
        raise ValueError('Users must have an email address')
    
    now = timezone.now()
    email = self.normalize_email(email).lower()

    user = self.model(
        email=email,
        last_login=now,
        date_joined=now, 
        **kwargs
    )
    user.set_password(password)
    user.save(using=self._db)
    return user


  def create_superuser(self, email, password, **extra_fields):
    user=self.create_user(email, password, **extra_fields)
    user.is_staff=True
    user.is_superuser=True
    user.save(using=self._db)
    return user



class UserAccount(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=254, unique=True)
    
    

    is_teacher = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    

    USERNAME_FIELD = 'email'
   

    objects = UserAccountManager()

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)

cookery/courses/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from courses.models import Course
from django.urls import reverse
# Create your views here.
from django.views import generic
from django.template import loader
from users.models import UserAccount

class CoursesView(generic.ListView):
    template_name = "courses/courses.html"
    context_object_name = "latest_courses_list"
    def get_queryset(self):
        """Return the last five published questions."""
        return  Course.objects.order_by("-date_created")[:5]
    
class InstructorView(generic.ListView):
    template_name = "courses/instructors.html"
    context_object_name = "instructor_list"

    def get_queryset(self):
        return  UserAccount.objects.all()
    
class CoutsesDetailsView(generic.DetailView):
    model = Course
    template_name = "courses/course_details.html"

class InstructorDetailsView(generic.DetailView):
    model = UserAccount
    template_name = "courses/instructor_details.html"


def add(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    course.details = request.POST["details"]
    course.name = request.POST["name"]
    course.save()
    print("Hello")
    return HttpResponseRedirect(reverse("courses:details", args=(course_id,)))

cookery/users/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the users index.")

cookery/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Cookery</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'courses:course'%} ">All Classes</a></li>
              <li><a href="{% url 'courses:instructor'%} ">All Instructor</a></li>
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
      </div>
    </div>
  </body>
</html>

cookery/templates/courses/course_details.html
{% extends "../base_generic.html" %}


{% block content %}
<form action="{% url 'courses:add' course.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ course.name }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <input type="text" name="details" id="details" value={{ course.details }}>
    
    <label>Details</label><br>

    <input type="text" name="name" id="name" value={{ course.name }}>
    <label>Name
    
</fieldset>
<input type="submit" value="Update">
</form>
{% endblock %}

cookery/templates/courses/courses.html
{% extends "../base_generic.html" %}


{% block content %}
  <h1>Cookery Home</h1>
  <p>
    Welcome to Cookery, a website developed by
    <em>Evren Bingol</em>!
  </p>
    {% if latest_courses_list %}
    <ul>
    {% for course in latest_courses_list %}
        <li><a href="{% url 'courses:course_details' course.id %}">{{ course.name }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No Classes are available.</p>
    {% endif %}
{% endblock %}

cookery/templates/courses/instructors.html
{% extends "../base_generic.html" %}


{% block content %}

    {% if instructor_list %}
    <ul>
    {% for instructor in instructor_list %}
        <li><a href="{% url 'courses:instructor_details' instructor.id %}">{{ instructor.email }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No Instructor are available.</p>
    {% endif %}
{% endblock %}

cookery/templates/courses/instuctor_details.html
{% extends "../base_generic.html" %}


{% block content %}
<legend><h1>{{ instructor.email }}</h1></legend>
{% endblock %}